### ISSUE TITLE
Test ADAPT installation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-parent#4]
The API endpoint is http://freme.adaptcentre.ie/freme

Please add some comments how to fix the problems if possible, e.g.

e-Link test fails
There are no e-Link templates in the database, so install the e-Link templates from this database dump: http:/...

Please add the issues and the fixes here in this issue.

**Comment by munnellg** [comment]
API endpoint is now http://freme.adaptcentre.ie/current

**Comment by bgrusdt** [comment]
These three tests fail on this API endpoint: [http://freme.adaptcentre.ie/current](http://freme.adaptcentre.ie/current).

1. e-link example API call
2. filter knowledgebase example
3. xslt converter - tei2temp-html example

For all three calls the respective data is missing. You have to load it into your freme mysql database. 
This is explained here: [https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/initialising-freme.html](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/initialising-freme.html)

There are init-templates that you can use to load the data into the database:
1. templates:
[https://raw.githubusercontent.com/freme-project/freme-packages/master/broker-local/src/main/resources/init-template.sql](https://raw.githubusercontent.com/freme-project/freme-packages/master/broker-local/src/main/resources/init-template.sql)

2.  sparqlconverters: 
[https://raw.githubusercontent.com/freme-project/freme-packages/master/broker-local/src/main/resources/init-sparqlconverter.sql](https://raw.githubusercontent.com/freme-project/freme-packages/master/broker-local/src/main/resources/init-sparqlconverter.sql)

3. xsltconverters:
[https://raw.githubusercontent.com/freme-project/freme-packages/master/broker-local/src/main/resources/init-xsltconverter.mysql.sql](https://raw.githubusercontent.com/freme-project/freme-packages/master/broker-local/src/main/resources/init-xsltconverter.mysql.sql)

With the following calls you can check if the templates, filters and xsltconverters are available:
````
curl -X GET "http://freme.adaptcentre.ie/current/e-link/templates"
curl -X GET  "http://freme.adaptcentre.ie/current/toolbox/convert/manage"
curl -X GET "http://freme.adaptcentre.ie/current/toolbox/xslt-converter/manage"
````

**Comment by jnehring** [comment]
all tests pass now
